### PR TITLE
switch to dune

### PR DESCRIPTION
**Pull request by redianthus**
Hi,

I switched the project to dune.

Cheers.

### CODE REVIEW

**Comment by xandkar** [comment]
Hi @zapashcanon,

Thank you for your help!

I can't merge it as-is, since it removes functionality from both the library and examples, but I can take a look at fixing that in your branch in the next few days.

**Comment by redianthus** [comment]
Oh sorry, I forgot that I changed a few stuff to get the library to compile, I'm going to fix this.

**Comment by redianthus** [comment]
I fixed the library.

The only thing left to do is to fix the second example, here: [this](https://github.com/khandkar/caravan/pull/13/files#diff-49a0af83dec2a33036cff8e26e216a4eR218), but I'm not familiar with Core or Async so if you can push a fix to my branch that would be nice. :)

**Comment by redianthus** [comment]
ping @xandkar

**Comment by xandkar** [comment]
Hello again @zapashcanon,

I finally had to admit that I no longer have time or interest to continue with this project. I disowned it in the opam repo:
https://github.com/ocaml/opam-repository/pull/18633
https://github.com/ocaml/opam-repository/blob/master/packages/caravan/caravan.0.0.2/opam

Please feel free to fork or delete it from the opam repo.

**Pull request closed without merging**
